default_stages: [ pre-commit ]
exclude: ^test/|core/migrations|api/migrations

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    args: [ '--unsafe' ]
  - id: check-merge-conflict
  - id: check-added-large-files
    args: ['--maxkb=1024']
  - id: pretty-format-json
    name: Format json files
    args: [ --autofix, --no-ensure-ascii, --no-sort-keys ]

- repo: https://github.com/asottile/pyupgrade
  rev: v2.37.3
  hooks:
  - id: pyupgrade
    args: [ --py38 ]

- repo: https://github.com/astral-sh/ruff-pre-commit # ruff includes black, isort, and flake8
  rev: v0.5.0
  hooks:
  - id: ruff
    args: [ --fix, --config=pyproject.toml ]
  - id: ruff-format
    args: [ --config=pyproject.toml ]


- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.1
  hooks:
  - id: mypy
    types: [ python ]
    additional_dependencies:
    - "pydantic>=2.5.2"
    - "types-requests >= 2.32"
    - "types-pyyaml >= 6.0"


# - repo: local
#   hooks:
#   - id: pytest-check
#     name: pytest-check
#     entry: pytest
#     types: [ python ]
#     language: system
#     pass_filenames: false
#     always_run: true

ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
