# config.yaml - Updated for LangGraph Documentation Processing

data_source:
  github:
    url: "https://github.com/langchain-ai/langgraph/tree/main/docs/docs"
    clone_url: "https://github.com/langchain-ai/langgraph.git"
    target_path: "docs/source_docs"
    local_cache: "langgraph_repo/docs/docs"

  file_filtering:
    included_formats:
      - ".md"          # Markdown files
      - ".ipynb"       # Jupyter notebooks
      - ".mdx"         # MDX files (if any)

    excluded_patterns:
      - "**/.*"                    # Hidden files
      - "**/__pycache__"          # Python cache
      - "**/node_modules"         # Node modules
      - "**/.git"                 # Git files
      - "**/test_*"               # Test files
      - "**/*test*"               # Any test-related files

document_processing:
  chunking:
    semantic : True  # Preserve semantic similarity
    chunk_size: 5000                # For recursive splitter fallback
    chunk_overlap: 600                # More overlap for context

    # Markdown-specific settings
    markdown:
      preserve_code_blocks: true
      code_fence_markers:
      - "```"
      - "~~~"
      headers_to_split: ["##", "###"]        # Split on h2 and h3
      preserve_tables: true

    # Notebook-specific settings
    notebook:
      extract_code_cells: true
      extract_markdown_cells: true
      preserve_cell_boundaries: true
      include_outputs: false           # Skip execution outputs
      max_cell_length: 2000

  metadata_extraction:
    standard_fields:
      - "file_path"
      - "file_type"
      - "section_title"
      - "cell_type"                   # For notebooks
      - "has_code_blocks"
      - "code_languages"

    code_analysis:
      detect_languages: true
      extract_imports: true
      extract_function_names: true
      api_pattern: "\\b[A-Z][a-zA-Z0-9_]*\\.[a-zA-Z_][a-zA-Z0-9_]*\\("   # FIXED: Match function calls
      class_pattern: "class\\s+([A-Z][a-zA-Z]*)"

# Vector Database Configuration
qdrant:
  connection:
    host: "localhost"
    port: 6333
    grpc_port: 6334
    api_key: ${QDRANT_API_KEY}        # Environment variable
    timeout: 30

  collection:
    name: "langgraph_docs"
    vector_dimension: 1536            # OpenAI text-embedding-3-small
    similarity_metric: "cosine"

    # Optimized for code and documentation
    indexing:
      hnsw:
        m: 32                         # Higher for better recall
        ef_construct: 200             # Better index quality
      quantization:
        scalar:
          enabled: true
          type: "int8"

# Embedding Configuration
embeddings:
  provider: "openai"
